# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GlossaryOfTerms\ui_files\enter_value_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EnterValueDialog(object):
    def setupUi(self, EnterValueDialog):
        EnterValueDialog.setObjectName("EnterValueDialog")
        EnterValueDialog.resize(311, 130)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EnterValueDialog.sizePolicy().hasHeightForWidth())
        EnterValueDialog.setSizePolicy(sizePolicy)
        EnterValueDialog.setMinimumSize(QtCore.QSize(311, 130))
        EnterValueDialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(EnterValueDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text_label = QtWidgets.QLabel(EnterValueDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.text_label.setFont(font)
        self.text_label.setObjectName("text_label")
        self.verticalLayout.addWidget(self.text_label)
        self.value_lineEdit = QtWidgets.QLineEdit(EnterValueDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.value_lineEdit.setFont(font)
        self.value_lineEdit.setPlaceholderText("")
        self.value_lineEdit.setObjectName("value_lineEdit")
        self.verticalLayout.addWidget(self.value_lineEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(EnterValueDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.error_label = QtWidgets.QLabel(EnterValueDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.error_label.setFont(font)
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.verticalLayout.addWidget(self.error_label)

        self.retranslateUi(EnterValueDialog)
        self.buttonBox.accepted.connect(EnterValueDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(EnterValueDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(EnterValueDialog)

    def retranslateUi(self, EnterValueDialog):
        _translate = QtCore.QCoreApplication.translate
        EnterValueDialog.setWindowTitle(_translate("EnterValueDialog", "Ввод значения"))
        self.text_label.setText(_translate("EnterValueDialog", "Введите значение:"))
