# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GlossaryOfTerms\ui_files\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1071, 752)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.labelSelectCourse = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSelectCourse.sizePolicy().hasHeightForWidth())
        self.labelSelectCourse.setSizePolicy(sizePolicy)
        self.labelSelectCourse.setMinimumSize(QtCore.QSize(0, 0))
        self.labelSelectCourse.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelSelectCourse.setFont(font)
        self.labelSelectCourse.setFrameShape(QtWidgets.QFrame.Box)
        self.labelSelectCourse.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelSelectCourse.setLineWidth(4)
        self.labelSelectCourse.setMidLineWidth(0)
        self.labelSelectCourse.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSelectCourse.setObjectName("labelSelectCourse")
        self.horizontalLayout_2.addWidget(self.labelSelectCourse)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tabWidgetMain = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidgetMain.setFont(font)
        self.tabWidgetMain.setObjectName("tabWidgetMain")
        self.verticalLayout.addWidget(self.tabWidgetMain)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1071, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidgetMain.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Glossary of Terms"))
        self.labelSelectCourse.setText(_translate("MainWindow", "Выберите курс"))
